server:
  port: 80
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: kitri1234
    key-password: kitri1234
    key-alias: spring

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://weatherwear.cybg4k8qmxa6.us-east-2.rds.amazonaws.com:3306/weatherwear?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 12345678
  messages:
    basename: messages
  profiles:
    include:
      - oauth
logging:
  level:
    ROOT: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
