server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weatherwear?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

logging:
  level:
    ROOT: DEBUG